FROM node:18-alpine

WORKDIR /cm-backend

COPY package.json .
RUN npm i --omit=dev

COPY dist dist

COPY .env .

COPY prisma prisma

RUN npx prisma generate
RUN npx prisma migrate deploy

CMD ["node", "dist/main/server.js"]
